# Generated by Django 3.2.12 on 2022-02-17 10:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import form_app.random_people.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Fish', 'Fish'), ('Parrot', 'Parrot'), ('Bunny', 'Bunny'), ('Pig', 'Pig')], max_length=6)),
                ('pet_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), form_app.random_people.validators.validate_name])),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), form_app.random_people.validators.validate_name])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), form_app.random_people.validators.validate_name])),
                ('egn', models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), form_app.random_people.validators.validate_egn])),
                ('job_title', models.CharField(choices=[('Waiter', 'Waiter'), ('Interpreter', 'Interpreter'), ('Driver', 'Driver'), ('Software Engineer', 'Software Engineer'), ('Teacher', 'Teacher'), ('Plumber', 'Plumber')], max_length=17)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='random_people.pet')),
            ],
        ),
    ]
