# Generated by Django 3.2.12 on 2022-02-17 14:52

import django.core.validators
from django.db import migrations, models
import form_app.random_people.validators


class Migration(migrations.Migration):

    dependencies = [
        ('random_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5), form_app.random_people.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(5), form_app.random_people.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(validators=[form_app.random_people.validators.validate_age]),
        ),
    ]
