# Generated by Django 3.2.12 on 2022-02-15 13:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('System Software', 'System Software'), ('Product Marketing', 'Product Marketing'), ('Security', 'Security'), ('Mobile App', 'Mobile App')], max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('egn', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='EGN')),
                ('job_title', models.CharField(choices=[('Software Developer', 'Software Developer'), ('QA Engineer', 'QA Engineer'), ('DevOps Specialist', 'DevOps Specialist')], max_length=18)),
                ('company', models.CharField(choices=[('SoftUni', 'SoftUni'), ('Google', 'Google'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=9)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
        ),
    ]
